hello admin<br>
<a href="{{ route('admin.adminAllocateCoopDeliveryTask') }}">adminAllocateCoopDeliveryTask</a><br>
<a href="{{ route('admin.adminEditAdminDrone',['id'=>1]) }}">adminEditAdminDrone</a><br>
<a href="{{ route('admin.adminEditCoopDroneInfo',['id'=>1]) }}">adminEditCoopDroneInfo</a><br>
<a href="{{ route('admin.adminEditCoopInfo',['id'=>1]) }}">adminEditCoopInfo</a><br>
<a href="{{ route('admin.adminEditCoopPayInfo',['id'=>1]) }}">adminEditCoopPayInfo</a><br>
<a href="{{ route('admin.adminEditUserInfo',['id'=>1]) }}">adminEditUserInfo</a><br>
<a href="{{ route('admin.adminLogin') }}">adminLogin</a><br>
<a href="{{ route('admin.adminLogout') }}">adminLogout</a><br>
<a href="{{ route('admin.adminRegisterAdminDrone') }}">adminRegisterAdminDrone</a><br>
<a href="{{ route('admin.adminViewUserPayInfo') }}">adminViewUserPayInfo</a><br>
<a href="{{ route('admin.adminViewUserStatisticsInfo') }}">adminViewUserStatisticsInfo</a><br>
<a href="{{ route('admin.adminViewUserStatisticsInfoGraph') }}">adminViewUserStatisticsInfoGraph</a><br>
<a href="{{ route('admin.adminSendCoopBill') }}">adminSendCoopBill</a><br>
<a href="{{ route('admin.adminSendUserBill') }}">adminSendUserBill</a><br>
<a href="{{ route('admin.adminViewCoopDroneInfo') }}">adminViewCoopDroneInfo</a><br>
<a href="{{ route('admin.adminViewCoopInfo') }}">adminViewCoopInfo</a><br>
<a href="{{ route('admin.adminViewCoopList') }}">adminViewCoopList</a><br>
<a href="{{ route('admin.adminViewUserDeliveryRequestList') }}">adminViewUserDeliveryRequestList</a><br>
<a href="{{ route('admin.adminViewCoopPayInfo') }}">adminViewCoopPayInfo</a><br>
<a href="{{ route('admin.adminViewCoopDeliveryRequestList') }}">adminViewCoopDeliveryRequestList</a><br>
<a href="{{ route('admin.adminViewCoopStatisticsInfo') }}">adminViewCoopStatisticsInfo</a><br>
<a href="{{ route('admin.adminViewCoopStatisticsInfoGraph') }}">adminViewCoopStatisticsInfoGraph</a><br>
<a href="{{ route('admin.adminViewUserInfo') }}">adminViewUserInfo</a><br>
<a href="{{ route('admin.adminViewUserList') }}">adminViewUserList</a><br>