version: '3'
services:
  app:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    volumes:
      - ./server:/path/in/container
  db:
    image: mysql:8.0.33
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: laravel_database
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./db/sql:/docker-entrypoint-initdb.d